"""ARC-AGI-3 submission agent: measured rules first, StochasticGoose otherwise.

GENERATED by build_hybrid.py -- edit agents/planner_agent.py or agents/goose_agent.py and
re-run the builder. Do not hand-edit: the two halves would drift.

Behaviour, measured:
  * where the derived rules apply, it plans and spends actions only on execution -- LS20
    level 1 is solved in the BFS-proven optimal 13 actions;
  * everywhere else it is the StochasticGoose CNN, unchanged, which scored 0.18 on the
    hidden set. The competition rerun uses a hidden game set, so the fallback is usually
    what runs, and it must be the thing that already scored rather than the novelty walk.
"""
from __future__ import annotations

WALL = 3
OBJ_COLOURS = (1,)
WALL_MIN = 20
MOVES = {1: (-1, 0), 2: (1, 0), 3: (0, -1), 4: (0, 1)}   # action -> (drow, dcol) in lattice cells
STEP = 5


# ── the model ────────────────────────────────────────────────────────────────────────────────
def _grid(frame: FrameData):
    a = np.asarray(frame.frame)
    return (a[-1] if a.ndim == 3 else a).astype(np.uint8)


def _find_block(g):
    """The movable block as an exact 5x5 stamp: two rows of 12 directly above three rows of 9.

    ⚠️ Matching on colour alone is wrong: colour 9 also draws the `@` patterns inside the panels, so
    a colour-based bounding box measures the whole board and never moves (F4b).
    """
    H, W = g.shape
    for r in range(H - 4):
        for c in range(W - 4):
            if np.all(g[r:r + 2, c:c + 5] == 12) and np.all(g[r + 2:r + 5, c:c + 5] == 9):
                return r, c
    return None


def _passable(g, r, c, start):
    if (r, c) == start:
        return True
    if not (0 <= r <= g.shape[0] - STEP and 0 <= c <= g.shape[1] - STEP):
        return False
    return int((g[r:r + 5, c:c + 5] == WALL).sum()) >= WALL_MIN


def _cells(start, H, W):
    rs = [start[0] + STEP * k for k in range(-12, 13) if 0 <= start[0] + STEP * k <= H - STEP]
    cs = [start[1] + STEP * k for k in range(-12, 13) if 0 <= start[1] + STEP * k <= W - STEP]
    return rs, cs


def _find_goal(g, start):
    """Lattice cells inside a colour-5 blob whose whole rim is WALL colour.

    Measured unique on LS20 level 1. The rigour matters: a panel whose rim is background -- a legend
    rather than a goal marker -- is excluded, which is what stops the bottom-left display being
    mistaken for the objective.
    """
    H, W = g.shape
    seen = np.zeros_like(g, dtype=bool)
    boxes = []
    for r0 in range(H):
        for c0 in range(W):
            if g[r0, c0] != 5 or seen[r0, c0]:
                continue
            q, comp = deque([(r0, c0)]), []
            seen[r0, c0] = True
            while q:
                y, x = q.popleft()
                comp.append((y, x))
                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    ny, nx = y + dy, x + dx
                    if 0 <= ny < H and 0 <= nx < W and not seen[ny, nx] and g[ny, nx] == 5:
                        seen[ny, nx] = True
                        q.append((ny, nx))
            ys = [p[0] for p in comp]
            xs = [p[1] for p in comp]
            a, b, c, d = min(ys), max(ys), min(xs), max(xs)
            ring = []
            if a - 1 >= 0:
                ring += [g[a - 1, x] for x in range(c, d + 1)]
            if b + 1 < H:
                ring += [g[b + 1, x] for x in range(c, d + 1)]
            if c - 1 >= 0:
                ring += [g[y, c - 1] for y in range(a, b + 1)]
            if d + 1 < W:
                ring += [g[y, d + 1] for y in range(a, b + 1)]
            if ring and len(comp) >= 9 and all(v == WALL for v in ring):
                boxes.append((a, b, c, d))
    rs, cs = _cells(start, H, W)
    out = []
    for r in rs:
        for c in cs:
            if (r, c) == start:
                continue
            for (a, b, cc, d) in boxes:
                if r >= a and r + 4 <= b and c >= cc and c + 4 <= d:
                    out.append((r, c))
                    break
    return out


def _find_collectibles(g, start):
    """Lattice cells containing a pixel of the object colour.

    ⚠️ Two earlier versions inferred "object" from the footprint's colour MIX and were wrong in both
    directions (F20a). Identifying the object by ITS OWN COLOUR is what is verified on both levels.
    """
    mask = np.isin(g, list(OBJ_COLOURS))
    if not mask.any():
        return []
    rs, cs = _cells(start, g.shape[0], g.shape[1])
    return [(r, c) for r in rs for c in cs
            if (r, c) != start and mask[r:r + 5, c:c + 5].any()]


def _plan_moves(g, start):
    """BFS over (cell, collected). Returns a list of action ids, or None.

    The state must include the collectibles taken, not just the cell: two routes reach LS20's
    (15,34) and behave differently there, because one of them took the pickup (F15).
    """
    goals = set(_find_goal(g, start))
    picks = set(_find_collectibles(g, start))
    if not goals:
        return None
    q = deque([(start, frozenset(), [])])
    seen = {(start, frozenset())}
    while q:
        (r, c), got, path = q.popleft()
        if (r, c) in goals and path and picks <= got:
            return path
        for aid, (dr, dc) in MOVES.items():
            nr, nc = r + dr * STEP, c + dc * STEP
            if not (0 <= nr <= g.shape[0] - STEP and 0 <= nc <= g.shape[1] - STEP):
                continue
            # the goal is enterable by definition: the wall rule rejects its panel interior
            if not (_passable(g, nr, nc, start) or (nr, nc) in goals):
                continue
            ngot = got | ({(nr, nc)} if (nr, nc) in picks else set())
            st = ((nr, nc), ngot)
            if st in seen:
                continue
            seen.add(st)
            q.append(((nr, nc), ngot, path + [aid]))
    return None


# =====================================================================
# StochasticGoose – CNN-based action learning agent
# Source: https://github.com/DriesSmit/ARC3-solution
# Authors: Dries Smit (Lead), Jack Cole (Adviser) — Tufa Labs
#
# Compatibility notes:
#   - Original uses `latest_frame.score` — replaced with `levels_completed`
#   - Original uses `latest_frame.available_actions` — gateway sends raw ints [1,2,...,6]
# =====================================================================
import hashlib
import logging
import os
import random
import time
import traceback
from collections import deque
from datetime import datetime
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from agents.agent import Agent
from arcengine import FrameData, GameAction, GameState


# --- Inlined from utils.py ---

def setup_experiment_directory(base_output_dir='runs'):
    """Create directories for outputs and logging."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_dir = os.path.join(base_output_dir, timestamp)
    os.makedirs(base_dir, exist_ok=True)
    log_file = os.path.join(base_dir, 'logs.log')
    print(f"Experiment directory created: {base_dir}")
    return base_dir, log_file


def get_environment_directory(base_dir, game_id):
    """Get or create environment-specific directory for a game_id."""
    env_dir = os.path.join(base_dir, game_id)
    os.makedirs(env_dir, exist_ok=True)
    return env_dir


def setup_logging_for_experiment(log_file_path):
    """Update logging configuration to use the experiment directory's log file."""
    root_logger = logging.getLogger()
    for handler in root_logger.handlers[:]:
        if isinstance(handler, logging.FileHandler):
            root_logger.removeHandler(handler)
            handler.close()
    formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
    file_handler = logging.FileHandler(log_file_path, mode="w")
    file_handler.setLevel(root_logger.level)
    file_handler.setFormatter(formatter)
    root_logger.addHandler(file_handler)


# --- ActionModel CNN ---

class ActionModel(nn.Module):
    """CNN that predicts which actions will result in new frames with shared conv backbone."""

    def __init__(self, input_channels=16, grid_size=64):
        super().__init__()
        self.grid_size = grid_size
        self.num_action_types = 5  # ACTION1-ACTION5

        # Shared convolutional backbone
        self.conv1 = nn.Conv2d(input_channels, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(128, 256, kernel_size=3, padding=1)

        # Action head
        self.action_pool = nn.MaxPool2d(4, 4)
        action_flattened_size = 256 * 16 * 16
        self.action_fc = nn.Linear(action_flattened_size, 512)
        self.action_head = nn.Linear(512, self.num_action_types)

        # Coordinate head (64x64 action space)
        self.coord_conv1 = nn.Conv2d(256, 128, kernel_size=3, padding=1)
        self.coord_conv2 = nn.Conv2d(128, 64, kernel_size=3, padding=1)
        self.coord_conv3 = nn.Conv2d(64, 32, kernel_size=1)
        self.coord_conv4 = nn.Conv2d(32, 1, kernel_size=1)

        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.relu(self.conv3(x))
        conv_features = F.relu(self.conv4(x))

        # Action head
        action_features = self.action_pool(conv_features)
        action_features = action_features.view(action_features.size(0), -1)
        action_features = F.relu(self.action_fc(action_features))
        action_features = self.dropout(action_features)
        action_logits = self.action_head(action_features)

        # Coordinate head
        coord_features = F.relu(self.coord_conv1(conv_features))
        coord_features = F.relu(self.coord_conv2(coord_features))
        coord_features = F.relu(self.coord_conv3(coord_features))
        coord_logits = self.coord_conv4(coord_features)
        coord_logits = coord_logits.view(coord_logits.size(0), -1)

        combined_logits = torch.cat([action_logits, coord_logits], dim=1)
        return combined_logits


# --- Action Agent (StochasticGoose) ---

class _Goose(Agent):
    """CNN-based action learning agent that predicts which actions cause frame changes."""

    MAX_ACTIONS = float('inf')
    _MAX_FRAMES = 10  # PERF: Keep only the last N frames (sliding window)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        seed = int(time.time() * 1000000) + hash(self.game_id) % 1000000
        random.seed(seed)
        np.random.seed(seed % (2**32 - 1))
        torch.manual_seed(seed % (2**32 - 1))
        self.start_time = time.time()

        # Device configuration
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        print(f"Action agent using device: {self.device}")

        # Setup experiment directory and logging
        self.base_dir, log_file = setup_experiment_directory()
        setup_logging_for_experiment(log_file)

        env_dir = get_environment_directory(self.base_dir, self.game_id)
        self.current_score = -1

        self.logger = logging.getLogger(f"ActionAgent_{self.game_id}")

        # Visualization disabled for submission
        self.save_action_visualizations = False

        # Initialize action model
        self.grid_size = 64
        self.num_coordinates = self.grid_size * self.grid_size
        self.num_colours = 16
        self.action_model = None
        self.optimizer = None

        # Experience buffer
        self.experience_buffer = deque(maxlen=200000)
        self.experience_hashes = set()
        self.batch_size = 64
        self.train_frequency = 5

        # Track previous state/action
        self.prev_frame = None
        self.prev_action_idx = None

        # Action mapping
        self.action_list = [GameAction.ACTION1, GameAction.ACTION2, GameAction.ACTION3,
                           GameAction.ACTION4, GameAction.ACTION5]

        self.log_dir = env_dir
        self.logger.info(f"Action agent initialized for game_id: {self.game_id}")

    def append_frame(self, frame: FrameData) -> None:
        """Override to cap frames list at _MAX_FRAMES (sliding window)."""
        self.frames.append(frame)
        if len(self.frames) > self._MAX_FRAMES:
            self.frames = self.frames[-self._MAX_FRAMES:]
        if frame.guid:
            self.guid = frame.guid
        if hasattr(self, "recorder") and not self.is_playback:
            import json
            self.recorder.record(json.loads(frame.model_dump_json()))

    def _get_score(self, frame):
        """Get score from frame, compatible with both patched and standard FrameData."""
        return getattr(frame, 'score', None) or frame.levels_completed

    def _sample_from_combined_output(self, combined_logits, available_actions=None):
        """Sample from combined 5 + 64x64 action space with masking for invalid actions."""
        action_logits = combined_logits[:5]
        coord_logits = combined_logits[5:]

        if available_actions is not None and len(available_actions) > 0:
            action_mask = torch.full_like(action_logits, float('-inf'))
            action6_available = False
            for action in available_actions:
                # Gateway sends raw ints [1,2,...,6], not GameAction enums
                action_id = action.value if hasattr(action, 'value') else int(action)
                if 1 <= action_id <= 5:
                    action_mask[action_id - 1] = 0.0
                elif action_id == 6:
                    action6_available = True
            action_logits = action_logits + action_mask
            if not action6_available:
                coord_logits = coord_logits + torch.full_like(coord_logits, float('-inf'))

        action_probs = torch.sigmoid(action_logits)
        coord_probs_raw = torch.sigmoid(coord_logits)
        coord_probs_scaled = coord_probs_raw / self.num_coordinates

        all_probs_sampling = torch.cat([action_probs, coord_probs_scaled])
        all_probs_sampling = all_probs_sampling / all_probs_sampling.sum()
        all_probs_sampling_np = all_probs_sampling.cpu().numpy()

        selected_idx = np.random.choice(len(all_probs_sampling_np), p=all_probs_sampling_np)

        coord_probs_viz = torch.sigmoid(coord_logits)
        all_probs_viz = torch.cat([action_probs, coord_probs_viz])
        all_probs_viz_np = all_probs_viz.cpu().numpy()

        if selected_idx < 5:
            return selected_idx, None, None, all_probs_viz_np
        else:
            coord_idx = selected_idx - 5
            y_idx = coord_idx // self.grid_size
            x_idx = coord_idx % self.grid_size
            return 5, (y_idx, x_idx), coord_idx, all_probs_viz_np

    def _frame_to_tensor(self, frame_data):
        """Convert frame data to tensor format for the model."""
        frame = np.array(frame_data.frame, dtype=np.int64)
        frame = frame[-1]
        assert frame.shape == (self.grid_size, self.grid_size), \
            f"Expected frame shape ({self.grid_size}, {self.grid_size}), got {frame.shape}"
        tensor = torch.zeros(self.num_colours, self.grid_size, self.grid_size, dtype=torch.float32)
        tensor.scatter_(0, torch.from_numpy(frame).unsqueeze(0), 1)
        return tensor.to(self.device)

    def _compute_experience_hash(self, frame, action_idx):
        """Compute hash for frame+action combination to ensure uniqueness."""
        frame_bytes = frame.tobytes()
        hash_input = frame_bytes + str(action_idx).encode('utf-8')
        return hashlib.md5(hash_input).hexdigest()

    def _train_action_model(self):
        """Train the action model on collected experiences."""
        if len(self.experience_buffer) < self.batch_size:
            return

        batch_indices = np.random.choice(len(self.experience_buffer), self.batch_size, replace=False)
        batch = [self.experience_buffer[i] for i in batch_indices]

        states = torch.stack([torch.from_numpy(exp['state']).float().to(self.device) for exp in batch])
        action_indices = torch.tensor([exp['action_idx'] for exp in batch], dtype=torch.long, device=self.device)
        rewards = torch.tensor([exp['reward'] for exp in batch], dtype=torch.float32, device=self.device)

        self.optimizer.zero_grad()

        combined_logits = self.action_model(states)
        selected_logits = combined_logits.gather(1, action_indices.unsqueeze(1)).squeeze(1)
        main_loss = F.binary_cross_entropy_with_logits(selected_logits, rewards)

        all_probs = torch.sigmoid(combined_logits)
        action_entropy = all_probs[:, :5].mean()
        coord_entropy = all_probs[:, 5:].mean()

        total_loss = main_loss - 0.0001 * action_entropy - 0.00001 * coord_entropy
        total_loss.backward()
        self.optimizer.step()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    def _has_time_elapsed(self):
        """Check if 8 hours have elapsed since start."""
        return (time.time() - self.start_time) >= 8 * 3600 - 5 * 60

    def is_done(self, frames, latest_frame):
        """Decide if the agent is done playing."""
        try:
            return any([
                latest_frame.state is GameState.WIN,
                self._has_time_elapsed(),
            ])
        except Exception as e:
            print(f"[DEBUG] is_done crashed: {e}")
            traceback.print_exc()
            return True  # bail out on error

    def choose_action(self, frames, latest_frame):
        """Choose action using action model predictions."""
        try:
            # DEBUG: Log frame info on first call
            if self.action_counter == 0:
                print(f"[DEBUG] latest_frame type: {type(latest_frame)}")
                print(f"[DEBUG] latest_frame.state: {latest_frame.state}")
                print(f"[DEBUG] latest_frame.levels_completed: {latest_frame.levels_completed}")
                print(f"[DEBUG] has score: {hasattr(latest_frame, 'score')}")
                print(f"[DEBUG] available_actions: {getattr(latest_frame, 'available_actions', 'N/A')}")
                if hasattr(latest_frame, 'frame') and latest_frame.frame:
                    frame_arr = np.array(latest_frame.frame)
                    print(f"[DEBUG] frame shape: {frame_arr.shape}")

            # Check if score/level has changed (triggers model reset for new level)
            current_level = self._get_score(latest_frame)
            if current_level != self.current_score:
                self.logger.info(f"Score changed from {self.current_score} to {current_level} at action {self.action_counter}")
                print(f"Score changed from {self.current_score} to {current_level} at action {self.action_counter}")

                self.experience_buffer.clear()
                self.experience_hashes.clear()
                print("Cleared experience buffer - new level reached")

                # Reset network and optimizer for new level
                self.action_model = ActionModel(input_channels=self.num_colours, grid_size=self.grid_size).to(self.device)
                self.optimizer = optim.Adam(self.action_model.parameters(), lr=0.0001)
                print("Reset action model and optimizer for new level")

                self.prev_frame = None
                self.prev_action_idx = None
                self.current_score = current_level

            if latest_frame.state in [GameState.NOT_PLAYED, GameState.GAME_OVER]:
                self.prev_frame = None
                self.prev_action_idx = None
                action = GameAction.RESET
                action.reasoning = "Game needs reset."
                return action

            # Convert current frame to tensor
            current_frame = self._frame_to_tensor(latest_frame)

            if current_frame is None:
                self.prev_frame = None
                self.prev_action_idx = None
                action = random.choice(self.action_list[:5])
                action.reasoning = f"Skipped weird frame, random {action.value}"
                return action

            # Create experience from previous action
            if self.prev_frame is not None:
                experience_hash = self._compute_experience_hash(self.prev_frame, self.prev_action_idx)
                if experience_hash not in self.experience_hashes:
                    current_frame_np = current_frame.cpu().numpy().astype(bool)
                    frame_changed = not np.array_equal(self.prev_frame, current_frame_np)
                    experience = {
                        'state': self.prev_frame,
                        'action_idx': self.prev_action_idx,
                        'reward': 1.0 if frame_changed else 0.0
                    }
                    self.experience_buffer.append(experience)
                    self.experience_hashes.add(experience_hash)

            # Get action predictions
            available_actions = getattr(latest_frame, 'available_actions', None)
            with torch.no_grad():
                combined_logits = self.action_model(current_frame.unsqueeze(0))
                combined_logits = combined_logits.squeeze(0)
                action_idx, coords, coord_idx, all_probs = self._sample_from_combined_output(
                    combined_logits, available_actions
                )

                if action_idx < 5:
                    selected_action = self.action_list[action_idx]
                    selected_action.reasoning = f"{selected_action.name} (prob: {all_probs[action_idx]:.3f})"
                else:
                    selected_action = GameAction.ACTION6
                    y, x = coords
                    selected_action.set_data({"x": int(x), "y": int(y)})
                    selected_action.reasoning = f"ACTION6 at ({x}, {y}) (prob: {all_probs[coord_idx]:.3f})"

            # Store current frame and action for next experience creation
            self.prev_frame = current_frame.cpu().numpy().astype(bool)
            if action_idx < 5:
                self.prev_action_idx = action_idx
            else:
                self.prev_action_idx = 5 + coord_idx

            # Train model periodically
            if self.action_counter % self.train_frequency == 0:
                self._train_action_model()

            return selected_action

        except Exception as e:
            print(f"[DEBUG] choose_action CRASHED at action {self.action_counter}: {type(e).__name__}: {e}")
            traceback.print_exc()
            # Fallback: return a random action so the agent doesn't die
            action = random.choice(self.action_list[:5])
            action.reasoning = f"Fallback after error: {e}"
            return action


# ── the hybrid ──────────────────────────────────────────────────────────────────
class MyAgent(_Goose):
    """Plan the level when the measured rules produce a plan; otherwise run the CNN unchanged.

    The CNN is inherited, not copied (see build_hybrid.py): `is_done`, `append_frame`, `MAX_ACTIONS`
    and the whole online learner come from `_Goose`, so the fallback is bit-for-bit the agent that
    scored 0.18 on the hidden set rather than a re-implementation of it.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._plan: list[int] = []
        self._at = 0
        self._plan_level = -1
        self.hybrid_report = {'planned_levels': 0, 'unplanned_levels': 0,
                              'planned_actions': 0, 'delegated_actions': 0}

    def _try_plan(self, frame: FrameData) -> None:
        """Build a plan for this level, or leave `self._plan` empty. Never raises.

        ⚠️ `unplanned_levels` counts EVERY level where no plan was produced, including the case where
        there is no block at all. The first version only counted the "found a block but no plan" case,
        so a game with no LS20-style block reported `unplanned_levels: 0` -- i.e. the counter was blind
        to the most common outcome, which is exactly the sort of reporting gap that makes a log say
        nothing happened when everything happened.
        """
        self._plan, self._at = [], 0
        try:
            g = _grid(frame)
            start = _find_block(g)
            if start is not None:
                acts = _plan_moves(g, start)
                if acts:
                    self._plan = acts
                    self.hybrid_report['planned_levels'] += 1
                    return
            self.hybrid_report['unplanned_levels'] += 1
        except Exception:
            self.hybrid_report['unplanned_levels'] += 1

    def choose_action(self, frames: list[FrameData], latest_frame: FrameData) -> GameAction:
        lvl = int(latest_frame.levels_completed or 0)
        if lvl != self._plan_level:
            self._plan_level = lvl
            self._try_plan(latest_frame)

        if self._at < len(self._plan):
            aid = self._plan[self._at]
            self._at += 1
            self.hybrid_report['planned_actions'] += 1
            a = GameAction.from_id(aid)
            a.reasoning = {'why': 'planned', 'step': self._at, 'of': len(self._plan), 'level': lvl}
            return a

        # Delegate. Note this is the ONLY place the CNN is reached, so during a planned level its
        # online learner sees no transitions -- acceptable because a planned level needs no learning.
        self.hybrid_report['delegated_actions'] += 1
        return super().choose_action(frames, latest_frame)
